/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Renderer {
  width: number
  height: number
  constructor(pInst: object, width: number, height: number, isMainCanvas: boolean)
  frame(): void
  startFrame(): void
  endFrame(): void
  _applyDefaults(): void
  resetMatrix(): void
  background(r: number, g: number, b: number): void
  rect(args: Array<number>): void
}

export interface RendererStates {
  strokeColor: string
  fillColor: string
  rectMode: string
}
